# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cfc0f412849017bfe2c460db5d3716989fb8a0b50dc027d65fe8cccb62aaf16d0e2a5d273fa2795820ac9a3b449417016522c0f96ec00e8413a0ef653c00886

test:
  secret_key_base: b572b4bca03207bdf3cd98c5f2f710aeb54a005d21590794f0cc98d0d8a6085ebae70417babfb1227e612bc89787ef5e5219798d9134713aa60738bc4589ee4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
